CREATE TABLE report_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  updtimestamp timestamp default SYSDATE,
  report_name VARCHAR(100) NOT NULL,
  report_description VARCHAR(500) NOT NULL,
  sql_description VARCHAR(1000) NOT NULL,
  PRIMARY KEY(id)
);